version: '2.1'
services:
  server:
    container_name: dh-chat-server
    #command: nodemon --debug=5859
    image: dh-chat:test
    build:
      context: .
      dockerfile: dh-chat.dockerfile
    ports:
      - 5858:5858
      - 5859:5859
    depends_on: 
      redis:
        condition: service_healthy
  redis:
    container_name: dh-chat-server-redis
    image: redis:3.2.11-alpine #dh-redis:alpine 
    # build:
    #   context: .
    #   dockerfile: redis.alpine.dockerfile
    ports:
      - 6379:6379
    healthcheck:
      test: "exit 0"
      interval: 3s
      timeout: 10s
      retries: 3

