version: '3'
services:
  socket:
    image: hub.donanimhaber.com:5000/dh-chat-socket-server:1.0-beta
    build:
      context: ../src/
      dockerfile: Dockerfile
    environment:
      - port=80
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 2
        delay: 2ms
    ports:
      - 5858:80
    depends_on: 
      - redis
      # redis:
      #   condition: service_healthy
  redis:
    image: redis:3.2.11-alpine
    healthcheck:
      test: "exit 0"
      interval: 3s
      timeout: 10s
      retries: 3

