version: '3'
services:
  server:
    container_name: dh-chat-server
    image: dh-chat:test
    build:
      context: ../src/
      dockerfile: Dockerfile
    environment:
      - port=80
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 2
        delay: 2ms
    ports:
      - 5858:80
    depends_on: 
      - redis
      # redis:
      #   condition: service_healthy
  redis:
    container_name: dh-chat-server-redis
    image: redis:3.2.11-alpine
    healthcheck:
      test: "exit 0"
      interval: 3s
      timeout: 10s
      retries: 3

